spring:
  application:
    name: chefduplacard

  datasource:
    url: ${APP_DB_URL:jdbc:postgresql://localhost:5432/chefduplacard}
    username: ${APP_DB_USER:chefduplacard}
    password: ${APP_DB_PASSWORD:chefduplacard}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  spring:
    jpa:
      open-in-view: false