CREATE TABLE unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(250) NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE aliment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    actif BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE recipe_type(
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name TEXT
);

CREATE TABLE recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    instructions TEXT NOT NULL,
    duration_minutes INTEGER,
    difficulty TEXT,
    recipe_type_id BIGINT NOT NULL,

    FOREIGN KEY (recipe_type_id) REFERENCES recipe_type(id)
);

CREATE TABLE ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipe(id) ON DELETE CASCADE,
    aliment_id BIGINT NOT NULL REFERENCES aliment(id),
    unit_id BIGINT NOT NULL REFERENCES unit(id),
    quantity_per_person NUMERIC(10,2) NOT NULL CHECK (quantity_per_person > 0),
    CONSTRAINT uk_ingredient_recipe_aliment UNIQUE (recipe_id, aliment_id)
);

CREATE TABLE stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name TEXT,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE  CASCADE,
    CONSTRAINT uk_stock_user UNIQUE (user_id)
);

CREATE TABLE stock_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES stock(id) ON DELETE CASCADE,
    aliment_id BIGINT NOT NULL REFERENCES aliment(id),
    unit_id BIGINT NOT NULL REFERENCES unit(id),
    quantity NUMERIC(10,2) NOT NULL CHECK (quantity >= 0),
    CONSTRAINT uk_stock_line UNIQUE (stock_id, aliment_id)
);