CREATE TABLE aliment_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE aliment_type_join (
    aliment_id BIGINT NOT NULL ,
    aliment_type_id BIGINT NOT NULL ,

    FOREIGN KEY (aliment_id) REFERENCES aliment(id)
        ON DELETE CASCADE,
    FOREIGN KEY (aliment_type_id) REFERENCES aliment_type(id)
        ON DELETE CASCADE,

    CONSTRAINT pk_aliment_type PRIMARY KEY (aliment_type_id, aliment_id)
);