CREATE TABLE pantry_staples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_pantrystaples UNIQUE (user_id)
);


CREATE TABLE pantry_staples_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pantry_staples_id BIGINT NOT NULL REFERENCES pantry_staples(id) ON DELETE CASCADE,
    aliment_id BIGINT NOT NULL REFERENCES aliment(id),
    unit_id BIGINT NOT NULL REFERENCES unit(id),
    quantity NUMERIC(10,2) NOT NULL CHECK (quantity >= 0),
    CONSTRAINT uk_staple_line UNIQUE (pantry_staples_id, aliment_id)
);

