CREATE TABLE shopping_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE shopping_list_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id BIGINT NOT NULL,
    aliment_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    quantity NUMERIC(10,2) NOT NULL CHECK (quantity > 0),

    FOREIGN KEY (shopping_list_id) REFERENCES shopping_list(id) ON DELETE CASCADE,
    FOREIGN KEY (aliment_id) REFERENCES aliment(id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id) REFERENCES unit(id) ON DELETE CASCADE
);

